common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 32
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 0            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     100.0
    extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ 0.999069 0.677958 -0.773462]
    extrinsic_R: [ 0.557268, 0.755406, -0.344695, 
                   -0.544121, 0.0186543, -0.838799, 
                   -0.627204, 0.654992, 0.421427]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

map_reuse:
    load_map_and_update: false
    map_path:  "/home/sunkejia/MyLib/P1/src/FAST_LIO/config/scans.pcd"
    origin_offset: 0.0
    # match_cut_len: 1000
    match_iteration_len: 0.5
    match_iteration_nums: 10
    frame0_thre: 5000
    setTransformationEpsilon: 0.01
    setStepSize: 0.1 
    setResolution: 1.0 
    setMaximumIterations: 50
    useOctree: true

